# Generated by Django 5.2 on 2025-05-12 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_account_account_type_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='account',
            name='last_activity',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opened_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('dormant', 'Dormant')], default='active', max_length=10),
        ),
    ]
