# Generated by Django 5.2.1 on 2025-05-26 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_account_interest_rate_account_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name': 'قيد يومية', 'verbose_name_plural': 'قيود اليومية'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterpart_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_transactions', to='accounting.account', verbose_name='The corresponding account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal_entry',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.journalentry'),
        ),
    ]
