# Generated by Django 5.2.1 on 2025-05-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_journalentry_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
    ]
