# Generated by Django 5.2.1 on 2025-06-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_journalentry_credit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer'), ('charging', 'Charging')], max_length=10, unique=True)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pourcentage de frais (%)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Frais fixes')),
                ('min_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Frais minimum')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration des frais',
                'verbose_name_plural': 'Configurations des frais',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='frais_operation',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name="Frais d'opération"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterpart_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_transactions', to='accounting.account', verbose_name='Compte correspondant'),
        ),
    ]
