# Generated by Django 5.2.1 on 2025-06-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_feesettings_transaction_frais_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='frais_operation',
        ),
        migrations.AlterField(
            model_name='feesettings',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer'), ('charging', 'Charging')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterpart_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_transactions', to='accounting.account', verbose_name='The corresponding account'),
        ),
    ]
