# Generated by Django 5.2.1 on 2025-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_transaction_frais_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesettings',
            name='min_fee',
        ),
        migrations.AddField(
            model_name='feesettings',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feesettings',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
    ]
