# Generated by Django 5.2.1 on 2025-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_remove_feesettings_min_fee_feesettings_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='frais_operation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="Frais d'opération"),
        ),
    ]
