# Generated by Django 5.2.1 on 2025-06-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_transaction_frais_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='counterpart_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_transactions', to='accounting.account', verbose_name='The corresponding account'),
        ),
    ]
