# Generated by Django 5.2.1 on 2025-06-24 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opened_date',
        ),
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='client_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('COMMERÇANT', 'Commerçant'), ('AGENCE', 'Agence')], default='CLIENT', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(default='2025-05-26', verbose_name='Date de création du compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='hold_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='hold_ecommerce',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'importation"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
