# Generated by Django 5.2.1 on 2025-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_remove_account_account_type_remove_account_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeSettings',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='montant',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='counterpart_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='frais_operation',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_agence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_banque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte_bancaire',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte_destinataire',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte_expediteur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nom_banque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nom_destinataire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nom_expediteur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tran_code',
            field=models.CharField(default='TR0700364', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tran_type',
            field=models.CharField(choices=[('ENVOI', 'Envoi'), ('PAIEMENT', 'Paiement'), ('COMP_VERSEMENT', 'Versement Compte'), ('COMP_RETRAIT', 'Retrait Compte'), ('RETRAIT', 'Retrait'), ('RECHARGE', 'Recharge'), ('PAIEMENT_CREDIT', 'Paiement Crédit'), ('PAIEMENT_FACTURE', 'Paiement Facture')], default='ENVOI', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
