# Generated by Django 5.2.1 on 2025-06-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_delete_feesettings_rename_amount_transaction_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
