# Generated by Django 5.2.1 on 2025-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
