# Generated by Django 5.2.1 on 2025-06-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_account_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission_agence',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_banque',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
