# Generated by Django 5.2.1 on 2025-06-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_transaction_commission_agence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission_agence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_banque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
