# Generated by Django 5.2.1 on 2025-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_transaction_commission_agence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Application name')),
                ('api_key', models.CharField(blank=True, max_length=255, unique=True, verbose_name='API Key')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='Secret Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_apps', to='accounting.customuser', verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Banking Application',
                'verbose_name_plural': 'Banking Applications',
            },
        ),
    ]
