# Generated by Django 5.2.1 on 2025-07-07 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_bankingapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='banking_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.bankingapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='banking_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='accounting.bankingapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='banking_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.bankingapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='banking_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounting.bankingapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='banking_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankingapp'),
            preserve_default=False,
        ),
    ]
